// Locks the game's numbers to evidence, and keeps the evidence in the repo.
//
//   node tools/balance.mjs            measure everything (about 10 min, all cores), rewrite docs/BALANCE.md + docs/balance.json
//   node tools/balance.mjs --quick    re-measure everything except the slow physics parts (about 1.5 min)
//   node tools/balance.mjs --check    CI mode: no writes. Fails if a balance number changed without the tables
//                                     being regenerated, if the quick tables drifted, or if a target is missed.
//
// The idea: someone should be able to retune a number next year without guessing what it was for. So every
// table in docs/BALANCE.md is generated by the code that plays the game, the numbers they were measured with
// are fingerprinted, and the targets they must meet are written down and enforced.
import fs from 'node:fs';
import crypto from 'node:crypto';
import { pool } from './lib/pool.mjs';
import { PROFILES } from './lib/runbot.mjs';
import { summarize } from './lib/runbot.mjs';
import { median } from './lib/stats.mjs';

const ROOT = new URL('../', import.meta.url);
const JSON_PATH = new URL('docs/balance.json', ROOT), MD_PATH = new URL('docs/BALANCE.md', ROOT);
const args = process.argv.slice(2);
const CHECK = args.includes('--check'), QUICK = args.includes('--quick') || CHECK, FULL_CHECK = args.includes('--full');
const pkg = JSON.parse(fs.readFileSync(new URL('package.json', ROOT), 'utf8'));
const old = fs.existsSync(JSON_PATH) ? JSON.parse(fs.readFileSync(JSON_PATH, 'utf8')) : null;
const log = (...a) => console.error(...a);

const BATTLE_STAGES = [1, 2, 3, 4, 5, 6, 8, 10, 12, 15];
const FAST_RUNS = 200, PHYS_RUNS = 12, CLAW_TRIALS = 300;
const RUN_PROFILES = { careful: 'careful', average: 'average', masher: 'masher', assisted: 'assisted',
  // the adversary: fight, retreat at the first scratch, collect what the ladder pays. Must never out-earn honest play.
  farm15: { ...PROFILES.average, farm: 0.15 }, farm50: { ...PROFILES.average, farm: 0.5 } };

async function measure() {
  const out = {};
  const t0 = Date.now();
  const step = (s) => log(`[${((Date.now() - t0) / 1000).toFixed(0)}s] ${s}`);

  step('fingerprint');
  const [{ data }] = await pool([{ fn: 'fingerprint' }], 1);
  out.fingerprint = crypto.createHash('sha1').update(JSON.stringify(data)).digest('hex').slice(0, 12);
  out.numbers = data;

  step('fights by party and stage');
  const jobs = [
    { fn: 'battles', args: { runs: 60, stages: BATTLE_STAGES } },
    { fn: 'battlesBestOf', args: { runs: 60, stages: BATTLE_STAGES, pick: 3 } },
    { fn: 'matchups', args: { runs: 60, stage: 6 } },
  ];
  const [battles, bestOf, matchups] = await pool(jobs, 3);
  out.battles = battles; out.battlesBestOf = bestOf; out.matchups = matchups;

  step(`whole runs, no-physics model, ${FAST_RUNS} per profile`);
  const CHUNK = 25, tasks = [];
  for (const [name, profile] of Object.entries(RUN_PROFILES)) for (let s = 0; s < FAST_RUNS; s += CHUNK) tasks.push({ fn: 'runs', args: { profile, fast: true, seeds: Array.from({ length: CHUNK }, (_, i) => 100 + s + i) } });
  const res = await pool(tasks);
  const byProfile = {};
  Object.keys(RUN_PROFILES).forEach((name, pi) => { byProfile[name] = res.slice(pi * (FAST_RUNS / CHUNK), (pi + 1) * (FAST_RUNS / CHUNK)).flat(); });
  out.econ = econTable(byProfile);

  if (!QUICK || FULL_CHECK) {
    step(`the claw, real physics, ${CLAW_TRIALS} grabs per profile`);
    out.claw = Object.fromEntries((await pool(Object.keys(PROFILES).map((profile) => ({ fn: 'claw', args: { profile, trials: CLAW_TRIALS } })))).map((r) => [r.profile, r]));
    step(`whole runs, real physics, ${PHYS_RUNS} per profile`);
    const pt = [];
    for (const profile of ['careful', 'average', 'masher', 'assisted']) for (let i = 0; i < PHYS_RUNS; i += 3) pt.push({ fn: 'runs', args: { profile, fast: false, seeds: [100 + i, 101 + i, 102 + i] } });
    const pr = await pool(pt);
    const pp = {};
    ['careful', 'average', 'masher', 'assisted'].forEach((name, pi) => { pp[name] = pr.slice(pi * (PHYS_RUNS / 3), (pi + 1) * (PHYS_RUNS / 3)).flat(); });
    out.econPhysics = econTable(pp);
  } else { out.claw = old && old.claw; out.econPhysics = old && old.econPhysics; }
  step('done');
  return out;
}

function econTable(byProfile) {
  const t = {};
  for (const [name, rs] of Object.entries(byProfile)) {
    const S = summarize(rs);
    const tokens = rs.reduce((a, r) => a + r.tokensEarned, 0), mins = rs.reduce((a, r) => a + r.playSeconds, 0) / 60;
    const avg = (f) => +(rs.reduce((a, r) => a + f(r), 0) / rs.length).toFixed(1);
    t[name] = { runs: rs.length, finished: S.finished, in30: S.finishedIn(30), in60: S.finishedIn(60), in90: S.finishedIn(90), medianMin: S.finishMin,
      reachedBoss1: Math.round(100 * rs.filter((r) => r.cleared >= 5).length / rs.length), medianCleared: S.medianCleared,
      grabs: avg((r) => r.grabs), fightsLost: avg((r) => r.fightsLost), retreats: avg((r) => r.retreats), lostParts: avg((r) => r.lostParts),
      tokensPerMin: +(tokens / mins).toFixed(2) };
  }
  return t;
}

// ----------------------------------------------------------------------- targets
// What the numbers are FOR. Each is a sentence a designer can argue with and a test the code can run.
function targets(d) {
  const E = d.econ, C = d.claw, T = [];
  const add = (name, ok, detail) => T.push({ name, ok: !!ok, detail });
  if (C) {
    const gap = C.careful.win - C.masher.win;
    add('The carry is a skill: a careful carrier wins at least 8 points more grabs than a masher', gap >= 8, `careful ${C.careful.win}% vs masher ${C.masher.win}% (gap ${gap})`);
    add('The assist is a fair helper: better than mashing, no better than careful play', C.assisted.win >= C.masher.win && C.assisted.win <= C.careful.win + 5, `masher ${C.masher.win}% < assisted ${C.assisted.win}% <= careful ${C.careful.win}% (+5 noise)`);
  }
  add('A careful player finishes a run (95% or more)', E.careful.finished >= 95, `${E.careful.finished}%`);
  add('An average player finishes a run (90% or more)', E.average.finished >= 90, `${E.average.finished}%`);
  add('A masher can still finish (40% or more), an assisted player too', E.masher.finished >= 40 && E.assisted.finished >= 40, `masher ${E.masher.finished}%, assisted ${E.assisted.finished}%`);
  add('A run takes 18 to 35 minutes for careful and average players (bot time, faster than a human)', [E.careful, E.average].every((x) => x.medianMin >= 18 && x.medianMin <= 35), `careful ${E.careful.medianMin} min, average ${E.average.medianMin} min`);
  add('No early wall: 95% of average players clear the first boss', E.average.reachedBoss1 >= 95, `${E.average.reachedBoss1}%`);
  add('Farming cannot beat playing: retreating at the first scratch earns less per minute than honest play', ['farm15', 'farm50'].every((k) => E[k].tokensPerMin <= E.average.tokensPerMin), `honest ${E.average.tokensPerMin}/min, farm15 ${E.farm15.tokensPerMin}, farm50 ${E.farm50.tokensPerMin}`);
  add('Nothing is wasted: no part physically leaves the machine in a real-physics run', !d.econPhysics || Object.values(d.econPhysics).every((x) => x.lostParts <= 0.5), d.econPhysics ? Object.entries(d.econPhysics).map(([k, x]) => `${k} ${x.lostParts}`).join(', ') : 'not measured');
  const cols = Object.keys(d.matchups[Object.keys(d.matchups)[0]]);
  const best = cols.map((c) => Object.entries(d.matchups).sort((a, b) => b[1][c].win - a[1][c].win || b[1][c].hpLeft - a[1][c].hpLeft)[0][0]);
  add('Build for the graveyard: no single build is best against every enemy', new Set(best).size > 1, cols.map((c, i) => `${c.trim()}: ${best[i]}`).join('; '));
  const bo = d.battlesBestOf.rows['3 creatures, 8 parts, best of 3'];
  add('A full party built from good picks beats stage 5 reliably and the final stage more often than not', bo[5] >= 95 && bo[15] >= 50, `stage 5: ${bo[5]}%, stage 15: ${bo[15]}%`);
  return T;
}

// ----------------------------------------------------------------------- markdown
const tab = (head, rows) => ['| ' + head.join(' | ') + ' |', '|' + head.map((_, i) => (i ? '---:' : '---')).join('|') + '|', ...rows.map((r) => '| ' + r.join(' | ') + ' |')].join('\n');
const md = {
  targets: (d) => tab(['', 'Target', 'Measured'], targets(d).map((t) => [t.ok ? '✅' : '❌', t.name, t.detail])),
  claw: (d) => (d.claw ? tab(['Player', 'Aim error', 'Carry', 'Grabs won', 'Kept once lifted'], Object.entries(d.claw).map(([k, c]) => [k, PROFILES[k].aimNoise + ' px', PROFILES[k].carry, c.win + '%', c.kept + '%'])) + `\n\n${CLAW_TRIALS} grabs each on fresh piles, real physics.` : '_not measured_'),
  battles: (d) => tab(['Party (random parts)', ...d.battles.stages.map((s) => 'S' + s)], Object.entries(d.battles.rows).map(([n, r]) => [n, ...d.battles.stages.map((s) => r[s] + '%')])) + '\n\n' + tab(['Party (best of 3 picks per slot)', ...d.battlesBestOf.stages.map((s) => 'S' + s)], Object.entries(d.battlesBestOf.rows).map(([n, r]) => [n, ...d.battlesBestOf.stages.map((s) => r[s] + '%')])),
  matchups: (d) => { const cols = Object.keys(d.matchups[Object.keys(d.matchups)[0]]); return tab(['Build (x3)', ...cols], Object.entries(d.matchups).map(([n, r]) => [n, ...cols.map((c) => `${r[c].win}% (${r[c].hpLeft}% HP left)`)])); },
  econ: (d) => tab(['Player', 'Finish', '≤30 min', '≤60 min', '≤90 min', 'Median (min)', 'Past boss 1', 'Grabs', 'Fights lost', 'Retreats', 'Tokens/min'], Object.entries(d.econ).map(([k, e]) => [k, e.finished + '%', e.in30 + '%', e.in60 + '%', e.in90 + '%', e.medianMin || '-', e.reachedBoss1 + '%', e.grabs, e.fightsLost, e.retreats, e.tokensPerMin])) + `\n\n${FAST_RUNS} runs each with the no-physics grab model (grab odds from the claw table).`,
  econPhysics: (d) => (d.econPhysics ? tab(['Player', 'Finish', 'Median (min)', 'Past boss 1', 'Grabs', 'Fights lost', 'Parts lost from machine'], Object.entries(d.econPhysics).map(([k, e]) => [k, e.finished + '%', e.medianMin || '-', e.reachedBoss1 + '%', e.grabs, e.fightsLost, e.lostParts])) + `\n\n${PHYS_RUNS} runs each with the real claw. Small samples: read these as "the model is not lying", not as precise rates.` : '_not measured_'),
  numbers: (d) => { const c = d.numbers.config, e = d.numbers.enemies; return tab(['Number', 'Value'], [
    ['Start tokens / win pay / restock', `${c.startTokens} / ${c.winTokens} + stage / ${c.restockParts} parts`],
    ['Partial pay (lost or retreated fight)', `${c.partialPay} x win pay x damage dealt, plus a ladder of up to ${c.ladderMax}`],
    ['Enemy growth per stage', `+${Math.round(c.enemyGrowth * 100)}% HP and ATK`],
    ['Wisp / Shade / Wraith HP', `${e.wisp.hp} / ${e.shade.hp} / ${e.wraith.hp}`],
    ['Shade armour', e.shade.def],
    ['Grab: carry momentum / steady speed / carry slip', `${c.carryAccel} px/s² / ${c.swingSafe} px/s / +${c.swingSlip} per s per 30 px/s over`],
    ['Grab: base slip / top jolt / twitch', `${c.slipBase}/s / ${c.topSlip} / ${c.twitchSlip}`],
    ['Assist speed', `${Math.round(c.assistSpeed * 100)}% of steady`],
    ['Stages', `${d.numbers.final}, bosses every 5th`],
    ['Fingerprint of all balance numbers', '`' + d.fingerprint + '`'],
  ]); },
};

function renderMarkdown(d) {
  let text = fs.readFileSync(MD_PATH, 'utf8');
  for (const [name, fn] of Object.entries(md)) {
    const re = new RegExp(`(<!-- BEGIN ${name} -->)[\\s\\S]*?(<!-- END ${name} -->)`);
    if (!re.test(text)) throw new Error(`docs/BALANCE.md has no <!-- BEGIN ${name} --> block`);
    text = text.replace(re, `$1\n${fn(d)}\n$2`);
  }
  return text;
}

// ---------------------------------------------------------------------- main
const fresh = await measure();
fresh.version = pkg.version;
const T = targets(fresh);
let bad = T.filter((t) => !t.ok);

if (CHECK) {
  const problems = [];
  if (!old) problems.push('docs/balance.json is missing: run node tools/balance.mjs');
  else {
    if (old.fingerprint !== fresh.fingerprint) problems.push(`balance numbers changed (fingerprint ${old.fingerprint} -> ${fresh.fingerprint}) but docs/BALANCE.md was measured with the old ones. Run node tools/balance.mjs and commit the result.`);
    const near = (a, b, tol) => Math.abs(a - b) <= tol;
    for (const [k, e] of Object.entries(fresh.econ)) { const o = old.econ && old.econ[k]; if (!o) continue; if (!near(e.finished, o.finished, 3)) problems.push(`econ ${k}: finish ${o.finished}% -> ${e.finished}%`); if (!near(e.medianMin, o.medianMin, 2)) problems.push(`econ ${k}: median ${o.medianMin} -> ${e.medianMin} min`); }
    for (const [n, r] of Object.entries(fresh.battles.rows)) for (const s of fresh.battles.stages) if (old.battles && old.battles.rows[n] && !near(r[s], old.battles.rows[n][s], 4)) problems.push(`battles ${n} S${s}: ${old.battles.rows[n][s]}% -> ${r[s]}%`);
    if (fs.readFileSync(MD_PATH, 'utf8') !== renderMarkdown(Object.assign({}, old, { numbers: old.numbers }))) problems.push('docs/BALANCE.md is not what docs/balance.json would generate (edited by hand inside a generated block?)');
  }
  for (const t of bad) problems.push('target missed: ' + t.name + ' (' + t.detail + ')');
  if (problems.length) { console.log('balance check FAILED\n - ' + problems.join('\n - ')); process.exit(1); }
  console.log(`balance check ok: fingerprint ${fresh.fingerprint}, ${T.length} targets met, tables match`);
} else {
  fresh.generated = new Date().toISOString().slice(0, 10);
  fresh.targets = T;
  fs.writeFileSync(JSON_PATH, JSON.stringify(fresh, null, 1) + '\n');
  fs.writeFileSync(MD_PATH, renderMarkdown(fresh));
  console.log(T.map((t) => `${t.ok ? 'ok  ' : 'MISS'} ${t.name}\n       ${t.detail}`).join('\n'));
  console.log(`\nwrote docs/BALANCE.md and docs/balance.json (fingerprint ${fresh.fingerprint})`);
  if (bad.length) { console.log(`\n${bad.length} target(s) missed`); process.exit(1); }
}
